services:

  postgres:
    image: pgvector/pgvector:pg16
    container_name: docuquery-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: docuquery
      POSTGRES_USER: your db username
      POSTGRES_PASSWORD: your db password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: